# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from unary.posts import unaryposts_pb2 as unaryposts__pb2


class UnaryPostsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_post = channel.unary_unary(
                '/unaryposts.UnaryPosts/create_post',
                request_serializer=unaryposts__pb2.Create.SerializeToString,
                response_deserializer=unaryposts__pb2.MessageResponse.FromString,
                )
        self.update_post = channel.unary_unary(
                '/unaryposts.UnaryPosts/update_post',
                request_serializer=unaryposts__pb2.Update.SerializeToString,
                response_deserializer=unaryposts__pb2.MessageResponse.FromString,
                )
        self.delete_post = channel.unary_unary(
                '/unaryposts.UnaryPosts/delete_post',
                request_serializer=unaryposts__pb2.Delete.SerializeToString,
                response_deserializer=unaryposts__pb2.MessageResponse.FromString,
                )
        self.get_post = channel.unary_unary(
                '/unaryposts.UnaryPosts/get_post',
                request_serializer=unaryposts__pb2.Get.SerializeToString,
                response_deserializer=unaryposts__pb2.PostResponse.FromString,
                )
        self.get_posts = channel.unary_unary(
                '/unaryposts.UnaryPosts/get_posts',
                request_serializer=unaryposts__pb2.GetAll.SerializeToString,
                response_deserializer=unaryposts__pb2.PostsResponse.FromString,
                )


class UnaryPostsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_posts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnaryPostsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_post': grpc.unary_unary_rpc_method_handler(
                    servicer.create_post,
                    request_deserializer=unaryposts__pb2.Create.FromString,
                    response_serializer=unaryposts__pb2.MessageResponse.SerializeToString,
            ),
            'update_post': grpc.unary_unary_rpc_method_handler(
                    servicer.update_post,
                    request_deserializer=unaryposts__pb2.Update.FromString,
                    response_serializer=unaryposts__pb2.MessageResponse.SerializeToString,
            ),
            'delete_post': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_post,
                    request_deserializer=unaryposts__pb2.Delete.FromString,
                    response_serializer=unaryposts__pb2.MessageResponse.SerializeToString,
            ),
            'get_post': grpc.unary_unary_rpc_method_handler(
                    servicer.get_post,
                    request_deserializer=unaryposts__pb2.Get.FromString,
                    response_serializer=unaryposts__pb2.PostResponse.SerializeToString,
            ),
            'get_posts': grpc.unary_unary_rpc_method_handler(
                    servicer.get_posts,
                    request_deserializer=unaryposts__pb2.GetAll.FromString,
                    response_serializer=unaryposts__pb2.PostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unaryposts.UnaryPosts', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnaryPosts(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unaryposts.UnaryPosts/create_post',
            unaryposts__pb2.Create.SerializeToString,
            unaryposts__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unaryposts.UnaryPosts/update_post',
            unaryposts__pb2.Update.SerializeToString,
            unaryposts__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete_post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unaryposts.UnaryPosts/delete_post',
            unaryposts__pb2.Delete.SerializeToString,
            unaryposts__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unaryposts.UnaryPosts/get_post',
            unaryposts__pb2.Get.SerializeToString,
            unaryposts__pb2.PostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_posts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unaryposts.UnaryPosts/get_posts',
            unaryposts__pb2.GetAll.SerializeToString,
            unaryposts__pb2.PostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
