# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unarystats.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10unarystats.proto\x12\nunarystats\"\x07\n\x05\x45mpty\"\x12\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x05\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x07TopPost\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"3\n\x0fTopPostResponse\x12 \n\x03top\x18\x01 \x03(\x0b\x32\x13.unarystats.TopPost\"(\n\x07TopUser\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"3\n\x0fTopUserResponse\x12 \n\x03top\x18\x01 \x03(\x0b\x32\x13.unarystats.TopUser2\xa1\x02\n\nUnaryStats\x12\x41\n\x0eget_post_stats\x12\x10.unarystats.Post\x1a\x1b.unarystats.MessageResponse\"\x00\x12\x46\n\x12get_post_top_likes\x12\x11.unarystats.Empty\x1a\x1b.unarystats.TopPostResponse\"\x00\x12\x46\n\x12get_post_top_views\x12\x11.unarystats.Empty\x1a\x1b.unarystats.TopPostResponse\"\x00\x12@\n\x0cget_user_top\x12\x11.unarystats.Empty\x1a\x1b.unarystats.TopUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unarystats_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=32
  _globals['_EMPTY']._serialized_end=39
  _globals['_POST']._serialized_start=41
  _globals['_POST']._serialized_end=59
  _globals['_MESSAGERESPONSE']._serialized_start=61
  _globals['_MESSAGERESPONSE']._serialized_end=95
  _globals['_TOPPOST']._serialized_start=97
  _globals['_TOPPOST']._serialized_end=149
  _globals['_TOPPOSTRESPONSE']._serialized_start=151
  _globals['_TOPPOSTRESPONSE']._serialized_end=202
  _globals['_TOPUSER']._serialized_start=204
  _globals['_TOPUSER']._serialized_end=244
  _globals['_TOPUSERRESPONSE']._serialized_start=246
  _globals['_TOPUSERRESPONSE']._serialized_end=297
  _globals['_UNARYSTATS']._serialized_start=300
  _globals['_UNARYSTATS']._serialized_end=589
# @@protoc_insertion_point(module_scope)
