# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from unary.stats import unarystats_pb2 as unarystats__pb2


class UnaryStatsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_post_stats = channel.unary_unary(
                '/unarystats.UnaryStats/get_post_stats',
                request_serializer=unarystats__pb2.Post.SerializeToString,
                response_deserializer=unarystats__pb2.MessageResponse.FromString,
                )
        self.get_post_top_likes = channel.unary_unary(
                '/unarystats.UnaryStats/get_post_top_likes',
                request_serializer=unarystats__pb2.Empty.SerializeToString,
                response_deserializer=unarystats__pb2.TopPostResponse.FromString,
                )
        self.get_post_top_views = channel.unary_unary(
                '/unarystats.UnaryStats/get_post_top_views',
                request_serializer=unarystats__pb2.Empty.SerializeToString,
                response_deserializer=unarystats__pb2.TopPostResponse.FromString,
                )
        self.get_user_top = channel.unary_unary(
                '/unarystats.UnaryStats/get_user_top',
                request_serializer=unarystats__pb2.Empty.SerializeToString,
                response_deserializer=unarystats__pb2.TopUserResponse.FromString,
                )


class UnaryStatsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_post_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_post_top_likes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_post_top_views(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_user_top(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnaryStatsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_post_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_post_stats,
                    request_deserializer=unarystats__pb2.Post.FromString,
                    response_serializer=unarystats__pb2.MessageResponse.SerializeToString,
            ),
            'get_post_top_likes': grpc.unary_unary_rpc_method_handler(
                    servicer.get_post_top_likes,
                    request_deserializer=unarystats__pb2.Empty.FromString,
                    response_serializer=unarystats__pb2.TopPostResponse.SerializeToString,
            ),
            'get_post_top_views': grpc.unary_unary_rpc_method_handler(
                    servicer.get_post_top_views,
                    request_deserializer=unarystats__pb2.Empty.FromString,
                    response_serializer=unarystats__pb2.TopPostResponse.SerializeToString,
            ),
            'get_user_top': grpc.unary_unary_rpc_method_handler(
                    servicer.get_user_top,
                    request_deserializer=unarystats__pb2.Empty.FromString,
                    response_serializer=unarystats__pb2.TopUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unarystats.UnaryStats', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnaryStats(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_post_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unarystats.UnaryStats/get_post_stats',
            unarystats__pb2.Post.SerializeToString,
            unarystats__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_post_top_likes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unarystats.UnaryStats/get_post_top_likes',
            unarystats__pb2.Empty.SerializeToString,
            unarystats__pb2.TopPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_post_top_views(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unarystats.UnaryStats/get_post_top_views',
            unarystats__pb2.Empty.SerializeToString,
            unarystats__pb2.TopPostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_user_top(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unarystats.UnaryStats/get_user_top',
            unarystats__pb2.Empty.SerializeToString,
            unarystats__pb2.TopUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
